apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest # from jaeger on docker hub
