apiVersion: batch/v1
kind: Job
metadata:
  name: package-installer-job
spec:
  template:
    spec:
      containers:
      - name: package-installer
        image: <Docker-Image>
        command: ["sh", "-c", "npm install --save @opentelemetry/api @opentelemetry/auto-instrumentations-node"]
      restartPolicy: OnFailure