receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4317"
      grpc:
        endpoint: "0.0.0.0:4318" 
processors:
  batch:
exporters:
  logging: # This exporter just logs the received telemetry for demo purposes
  otlphttp:
    endpoint: "http://host.docker.internal:3001/v1/traces"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
