apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: rbrtm984/easy-court

# create cluster with --config=/yaml-folder/demo-app-setup/kind-config.yaml
# then #
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml
# then #
# kubectl apply -f yaml-folder/demo-app-setup/cluster-admin.yaml && kubectl apply -f yaml-folder/demo-app-setup/dashboard-adminuser.yaml && kubectl apply -f yaml-folder/demo-app-setup/easy-court-deployment.yaml && kubectl apply -f yaml-folder/demo-app-setup/service-account.yaml